# Generated by Django 3.0.2 on 2020-02-14 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('intro', models.TextField()),
                ('production_capacity_technology_process', models.TextField()),
                ('image', models.ImageField(upload_to='staticfiles/products/images')),
            ],
        ),
        migrations.CreateModel(
            name='DirectCosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=70)),
                ('units', models.CharField(max_length=70)),
                ('at', models.FloatField()),
                ('qty_day', models.FloatField()),
                ('production_cost_day', models.FloatField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processor.Business')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralCosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=70)),
                ('production_cost_month', models.FloatField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processor.Business')),
            ],
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=70)),
                ('office_contact', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='SourceEquipmentMaterials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=270)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processor.Business')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('responsible_ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processor.Ministry')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectProductCostPriceStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=70)),
                ('qty_day', models.IntegerField()),
                ('at', models.FloatField()),
                ('production_cost_yr', models.FloatField()),
                ('unit_price', models.FloatField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processor.Business')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionOperatingCosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processor.Business')),
                ('direct_overheads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processor.DirectCosts')),
                ('general_costs_overheads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processor.GeneralCosts')),
            ],
        ),
        migrations.CreateModel(
            name='MarketAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processor.Business')),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentFacilitiesIncentives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processor.Business')),
            ],
        ),
        migrations.CreateModel(
            name='CapitalInvestmentRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField()),
                ('unit', models.TextField()),
                ('qty', models.IntegerField()),
                ('at', models.FloatField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processor.Business')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processor.Sector'),
        ),
    ]
