# Generated by Django 3.0.2 on 2020-03-23 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalInvestmentRequirementsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('units', models.CharField(max_length=70)),
                ('qty', models.FloatField()),
                ('at', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DirectCostsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('units', models.CharField(blank=True, max_length=70, null=True)),
                ('at', models.FloatField()),
                ('qty', models.FloatField()),
                ('month_days', models.IntegerField()),
                ('production_cost_month', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralCostsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('production_cost_month', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectProductCostPriceStructureItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('at', models.FloatField(blank=True, null=True)),
                ('qty_day', models.FloatField(blank=True, null=True)),
                ('production_cost_day', models.FloatField(blank=True, null=True)),
                ('unit_price', models.FloatField(blank=True, null=True)),
                ('period', models.IntegerField(blank=True, null=True)),
                ('output', models.FloatField(blank=True, null=True)),
                ('unit_cost', models.FloatField(blank=True, null=True)),
                ('month_days', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='capitalinvestmentrequirements',
            old_name='business',
            new_name='Business',
        ),
        migrations.RenameField(
            model_name='directcosts',
            old_name='business',
            new_name='Business',
        ),
        migrations.RenameField(
            model_name='generalcosts',
            old_name='business',
            new_name='Business',
        ),
        migrations.RenameField(
            model_name='governmentfacilitiesincentives',
            old_name='business',
            new_name='Business',
        ),
        migrations.RenameField(
            model_name='marketanalysis',
            old_name='business',
            new_name='Business',
        ),
        migrations.RenameField(
            model_name='productionoperatingcosts',
            old_name='business',
            new_name='Business',
        ),
        migrations.RenameField(
            model_name='projectproductcostpricestructure',
            old_name='business',
            new_name='Business',
        ),
        migrations.RenameField(
            model_name='sourceequipmentmaterials',
            old_name='business',
            new_name='Business',
        ),
        migrations.RemoveField(
            model_name='capitalinvestmentrequirements',
            name='at',
        ),
        migrations.RemoveField(
            model_name='capitalinvestmentrequirements',
            name='item',
        ),
        migrations.RemoveField(
            model_name='capitalinvestmentrequirements',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='capitalinvestmentrequirements',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='directcosts',
            name='at',
        ),
        migrations.RemoveField(
            model_name='directcosts',
            name='item',
        ),
        migrations.RemoveField(
            model_name='directcosts',
            name='production_cost_day',
        ),
        migrations.RemoveField(
            model_name='directcosts',
            name='qty_day',
        ),
        migrations.RemoveField(
            model_name='directcosts',
            name='units',
        ),
        migrations.RemoveField(
            model_name='generalcosts',
            name='item',
        ),
        migrations.RemoveField(
            model_name='generalcosts',
            name='production_cost_month',
        ),
        migrations.RemoveField(
            model_name='projectproductcostpricestructure',
            name='at',
        ),
        migrations.RemoveField(
            model_name='projectproductcostpricestructure',
            name='item',
        ),
        migrations.RemoveField(
            model_name='projectproductcostpricestructure',
            name='production_cost_yr',
        ),
        migrations.RemoveField(
            model_name='projectproductcostpricestructure',
            name='qty_day',
        ),
        migrations.RemoveField(
            model_name='projectproductcostpricestructure',
            name='unit_price',
        ),
        migrations.AlterField(
            model_name='business',
            name='image',
            field=models.ImageField(upload_to='Farm/static/processor'),
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('Business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processor.Business')),
            ],
        ),
        migrations.AddField(
            model_name='capitalinvestmentrequirements',
            name='name',
            field=models.ManyToManyField(to='processor.CapitalInvestmentRequirementsItem'),
        ),
        migrations.AddField(
            model_name='directcosts',
            name='name',
            field=models.ManyToManyField(to='processor.DirectCostsItem'),
        ),
        migrations.AddField(
            model_name='generalcosts',
            name='name',
            field=models.ManyToManyField(to='processor.GeneralCostsItem'),
        ),
        migrations.AddField(
            model_name='projectproductcostpricestructure',
            name='name',
            field=models.ManyToManyField(to='processor.ProjectProductCostPriceStructureItem'),
        ),
    ]
