# Generated by Django 3.0.2 on 2020-04-02 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0002_auto_20200323_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['-sector'], 'verbose_name': 'Business', 'verbose_name_plural': 'Businesses'},
        ),
    ]
