# Generated by Django 3.0.2 on 2020-06-15 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0003_auto_20200402_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name': 'Business', 'verbose_name_plural': 'Businesses'},
        ),
    ]
