# Generated by Django 3.0.8 on 2020-09-07 14:45

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotspot', '0002_auto_20200906_0605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(blank=True, choices=[('petrol', 'petrol'), ('disiel', 'disiel'), ('gas', 'gas')], default='petrol', max_length=100, null=True)),
                ('quantity', models.FloatField(blank=True, max_length=100, null=True)),
                ('order_placed_date', models.DateTimeField(auto_now=True)),
                ('order_pickup_date', models.DateTimeField()),
                ('order_expire_date', models.DateTimeField()),
                ('customer', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('hotspot', models.ManyToManyField(to='hotspot.Hotspot')),
            ],
        ),
        migrations.CreateModel(
            name='OrdersDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_delivery_date', models.DateTimeField()),
                ('order_delivery_courierState', models.CharField(blank=True, choices=[('pickupPoint', 'pickupPoint'), ('intransit', 'intransit'), ('delivered', 'delivered'), ('returning', 'returning'), ('returned', 'returned')], default='pickupPoint', max_length=100, null=True)),
                ('order_delivery_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('order_delivery_city', models.CharField(blank=True, choices=[('Gweru', 'Gweru'), ('Harare', 'Harare'), ('Mutare', 'Mutare'), ('Bulawayo', 'Bulawayo'), ('Victoria Falls', 'Victoria_Falls'), ('Beitbridge', 'Beitbridge')], default='Gweru', max_length=100, null=True)),
                ('order_delivery_residence', models.CharField(blank=True, max_length=100, null=True)),
                ('order_delivery_neigbhourhood', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.ManyToManyField(to='hotspot.Orders')),
            ],
        ),
    ]
